### PR TITLE
fix(*): resolve lint warning

### PR DESCRIPTION
**Pull request by lichuan0620**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @your-reviewer

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by supereagle** [comment]
lint 还是不过

image

**Comment by lichuan0620** [comment]
@supereagle 好了，之前是流水线没配好

**Pull request merged**
